language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: murray@avantgardeweb.co.uk
  api_key: $NPM_TOKEN
  on:
    branch: master
  skip_cleanup: true
  tag: latest
after_deploy:
  - npm run deploy